// evaluation/svelte/src/lib/Login.svelte
<script lang="ts">
    import {session} from "../session.svelte";
    import {Session} from "wordle-lib";
    import {push} from "svelte-spa-router";

    let username = session.current?.username ?? "";

    /**
     * Creates a new session with the provided username and navigates to the game page.
     * If the username is empty, an alert is shown to the user.
     */
    function createSession() {
        username = username.trim();
        if(username.length === 0) {
            alert("Please enter a username");
            return;
        }

        session.current = new Session(username);
        sessionStorage.setItem("username", username);
        console.log(session.current);
        push("/game");
    }

</script>

<section>
    <label for="username">Username</label>
    <input bind:value="{username}" name="username" type="text">
    <button on:click={createSession} id="submit">Play</button>
</section>

// evaluation/web-components/src/components/login.ts
import {EventEmitter} from "../eventEmitter.ts";
import {Session} from "wordle-lib";

export class WordleLogin extends HTMLElement {

    private readonly loggedInEvent = new EventEmitter<Session>();
    public readonly onLoggedIn = this.loggedInEvent.readonlyEmitter;

    public set session(session: Session | undefined) {
        const input = this.querySelector('input[name="username"]') as HTMLInputElement;
        input.value = session?.username ?? "";
    }

    connectedCallback() {
        this.innerHTML = `
        <section>
            <label for="username">Username</label>
            <input name="username" type="text">
            <button id="submit">Play</button>
        </section>
        `;

        const button = this.querySelector('#submit');
        const input = this.querySelector('input[name="username"]') as HTMLInputElement;

        /* init session on name enter */
        button.addEventListener('click', () => {
            const username = input.value.trim();
            if(username.length === 0) {
                alert("Please enter a username.");
                return;
            }
            sessionStorage.username = username;
            const newSession = new Session(username);
            newSession.startNewGame();

            this.loggedInEvent.emit(newSession);
            window.location.hash = "/play";
        });
    }
}

customElements.define('wordle-login', WordleLogin);
